// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHlaDx2Yord0jEPNgkJCSwMQI7NkzAWR0',
    appId: '1:164031486905:web:8f96542a9e32d8147f3468',
    messagingSenderId: '164031486905',
    projectId: 'technical-test-e1092',
    authDomain: 'technical-test-e1092.firebaseapp.com',
    storageBucket: 'technical-test-e1092.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLUoxkCkTHR8S8KwoecfU2gQvz0eany88',
    appId: '1:164031486905:android:ae7947fbe97538b47f3468',
    messagingSenderId: '164031486905',
    projectId: 'technical-test-e1092',
    storageBucket: 'technical-test-e1092.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClZkyLXXJWQLFwonL5y0txvIRuscpt0ig',
    appId: '1:164031486905:ios:df8f2761d15b7d997f3468',
    messagingSenderId: '164031486905',
    projectId: 'technical-test-e1092',
    storageBucket: 'technical-test-e1092.appspot.com',
    iosBundleId: 'com.example.technicalTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClZkyLXXJWQLFwonL5y0txvIRuscpt0ig',
    appId: '1:164031486905:ios:80c86e572bdd7b527f3468',
    messagingSenderId: '164031486905',
    projectId: 'technical-test-e1092',
    storageBucket: 'technical-test-e1092.appspot.com',
    iosBundleId: 'com.example.technicalTest.RunnerTests',
  );
}
